//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  dinner_party: Dinner_Party;
  dinner_partyConnection: Dinner_PartyConnection;
  out_on_the_town: Out_On_The_Town;
  out_on_the_townConnection: Out_On_The_TownConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDinner_PartyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDinner_PartyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Dinner_PartyFilter>;
};


export type QueryOut_On_The_TownArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryOut_On_The_TownConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Out_On_The_TownFilter>;
};

export type DocumentFilter = {
  dinner_party?: InputMaybe<Dinner_PartyFilter>;
  out_on_the_town?: InputMaybe<Out_On_The_TownFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Dinner_Party | Out_On_The_Town | Folder;

export type Dinner_Party = Node & Document & {
  __typename?: 'Dinner_party';
  title: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Dinner_PartyFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  description?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type Dinner_PartyConnectionEdges = {
  __typename?: 'Dinner_partyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Dinner_Party>;
};

export type Dinner_PartyConnection = Connection & {
  __typename?: 'Dinner_partyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Dinner_PartyConnectionEdges>>>;
};

export type Out_On_The_Town = Node & Document & {
  __typename?: 'Out_on_the_town';
  title: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Out_On_The_TownFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  description?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type Out_On_The_TownConnectionEdges = {
  __typename?: 'Out_on_the_townConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Out_On_The_Town>;
};

export type Out_On_The_TownConnection = Connection & {
  __typename?: 'Out_on_the_townConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Out_On_The_TownConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateDinner_party: Dinner_Party;
  createDinner_party: Dinner_Party;
  updateOut_on_the_town: Out_On_The_Town;
  createOut_on_the_town: Out_On_The_Town;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateDinner_PartyArgs = {
  relativePath: Scalars['String']['input'];
  params: Dinner_PartyMutation;
};


export type MutationCreateDinner_PartyArgs = {
  relativePath: Scalars['String']['input'];
  params: Dinner_PartyMutation;
};


export type MutationUpdateOut_On_The_TownArgs = {
  relativePath: Scalars['String']['input'];
  params: Out_On_The_TownMutation;
};


export type MutationCreateOut_On_The_TownArgs = {
  relativePath: Scalars['String']['input'];
  params: Out_On_The_TownMutation;
};

export type DocumentUpdateMutation = {
  dinner_party?: InputMaybe<Dinner_PartyMutation>;
  out_on_the_town?: InputMaybe<Out_On_The_TownMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  dinner_party?: InputMaybe<Dinner_PartyMutation>;
  out_on_the_town?: InputMaybe<Out_On_The_TownMutation>;
};

export type Dinner_PartyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Out_On_The_TownMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Dinner_PartyPartsFragment = { __typename: 'Dinner_party', title: string, date?: string | null, description?: string | null, body?: any | null };

export type Out_On_The_TownPartsFragment = { __typename: 'Out_on_the_town', title: string, date?: string | null, description?: string | null, body?: any | null };

export type Dinner_PartyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Dinner_PartyQuery = { __typename?: 'Query', dinner_party: { __typename: 'Dinner_party', id: string, title: string, date?: string | null, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Dinner_PartyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Dinner_PartyFilter>;
}>;


export type Dinner_PartyConnectionQuery = { __typename?: 'Query', dinner_partyConnection: { __typename?: 'Dinner_partyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Dinner_partyConnectionEdges', cursor: string, node?: { __typename: 'Dinner_party', id: string, title: string, date?: string | null, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Out_On_The_TownQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Out_On_The_TownQuery = { __typename?: 'Query', out_on_the_town: { __typename: 'Out_on_the_town', id: string, title: string, date?: string | null, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Out_On_The_TownConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Out_On_The_TownFilter>;
}>;


export type Out_On_The_TownConnectionQuery = { __typename?: 'Query', out_on_the_townConnection: { __typename?: 'Out_on_the_townConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Out_on_the_townConnectionEdges', cursor: string, node?: { __typename: 'Out_on_the_town', id: string, title: string, date?: string | null, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const Dinner_PartyPartsFragmentDoc = gql`
    fragment Dinner_partyParts on Dinner_party {
  __typename
  title
  date
  description
  body
}
    `;
export const Out_On_The_TownPartsFragmentDoc = gql`
    fragment Out_on_the_townParts on Out_on_the_town {
  __typename
  title
  date
  description
  body
}
    `;
export const Dinner_PartyDocument = gql`
    query dinner_party($relativePath: String!) {
  dinner_party(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Dinner_partyParts
  }
}
    ${Dinner_PartyPartsFragmentDoc}`;
export const Dinner_PartyConnectionDocument = gql`
    query dinner_partyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Dinner_partyFilter) {
  dinner_partyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Dinner_partyParts
      }
    }
  }
}
    ${Dinner_PartyPartsFragmentDoc}`;
export const Out_On_The_TownDocument = gql`
    query out_on_the_town($relativePath: String!) {
  out_on_the_town(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Out_on_the_townParts
  }
}
    ${Out_On_The_TownPartsFragmentDoc}`;
export const Out_On_The_TownConnectionDocument = gql`
    query out_on_the_townConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Out_on_the_townFilter) {
  out_on_the_townConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Out_on_the_townParts
      }
    }
  }
}
    ${Out_On_The_TownPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      dinner_party(variables: Dinner_PartyQueryVariables, options?: C): Promise<{data: Dinner_PartyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Dinner_PartyQueryVariables, query: string}> {
        return requester<{data: Dinner_PartyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Dinner_PartyQueryVariables, query: string}, Dinner_PartyQueryVariables>(Dinner_PartyDocument, variables, options);
      },
    dinner_partyConnection(variables?: Dinner_PartyConnectionQueryVariables, options?: C): Promise<{data: Dinner_PartyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Dinner_PartyConnectionQueryVariables, query: string}> {
        return requester<{data: Dinner_PartyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Dinner_PartyConnectionQueryVariables, query: string}, Dinner_PartyConnectionQueryVariables>(Dinner_PartyConnectionDocument, variables, options);
      },
    out_on_the_town(variables: Out_On_The_TownQueryVariables, options?: C): Promise<{data: Out_On_The_TownQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Out_On_The_TownQueryVariables, query: string}> {
        return requester<{data: Out_On_The_TownQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Out_On_The_TownQueryVariables, query: string}, Out_On_The_TownQueryVariables>(Out_On_The_TownDocument, variables, options);
      },
    out_on_the_townConnection(variables?: Out_On_The_TownConnectionQueryVariables, options?: C): Promise<{data: Out_On_The_TownConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Out_On_The_TownConnectionQueryVariables, query: string}> {
        return requester<{data: Out_On_The_TownConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Out_On_The_TownConnectionQueryVariables, query: string}, Out_On_The_TownConnectionQueryVariables>(Out_On_The_TownConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  