[build]
  publish = "public"
  command = "tinacms build && hugo --minify --baseURL https://ralphskitchen.netlify.app/"

[build.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_ENVIRONMENT = "production"
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "TINA_TOKEN"
