backend:
  name: git-gateway
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: dgdmgrse0
    upload_preset: ralphs kitchen

collections:
  - name: "dinner-party"
    label: "Dinner Party"
    folder: "content/dinner-party"
    create: true
    path: "{{slug}}/index"
    fields:
      - { label: "Title",       name: "title",       widget: "string" }
      - { label: "Date",        name: "date",        widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Description", name: "description", widget: "string",   required: false }
      - { label: "Body",        name: "body",        widget: "markdown" }

  - name: "out-on-the-town"
    label: "Out on the Town"
    folder: "content/out-on-the-town"
    create: true
    path: "{{slug}}/index"
    fields:
      - { label: "Title",       name: "title",       widget: "string" }
      - { label: "Date",        name: "date",        widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Description", name: "description", widget: "string",   required: false }
      - { label: "Body",        name: "body",        widget: "markdown" }
